config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :articles do
     resources :votes
  end

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :user
  has_many :votes

  validates :user_id, presence: true

  def net_vote_count
    votes.upvotes.count - votes.downvotes.count
  end

end # end of class

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         # added this for Twitter access
         :omniauthable

  has_many :articles

  def self.twitter_auth(auth_hash) # pass in Twitter auth hash
    # see gem omniauth-twitter docs for this:-
    user = find_or_create_by(uid: auth_hash[:uid], provider: :twitter) do |user|
      user.name = auth_hash[:info][:name]
      # dummy data for Devise so user can be signed in
      user.password = nil
      user.password_confirmation = nil
    end
  end

  def email_required? # overides Devise method
    return false if provider == 'twitter'
    super # superclass method which returns 'true'!
  end

end # of class

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :article

  validates :article_id, presence: true

  # Rails scope method allows an object to be passed to the Proc
  scope :upvotes,  -> { where(up: true) }
  scope :downvotes,  -> { where(up: false) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article].permit(:content))
    current_user.articles << @article
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end


  def index
    @articles = Article.all
  end

end # of class

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController

  # method added by Devise :) called by twitter upon successful authentication
  def twitter
    user = User.twitter_auth(request.env['omniauth.auth']) # gets auth hash from Twitter
    # tell Devise to sign user in and redirect
    sign_in_and_redirect user
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @vote = Vote.create(article: @article, up: params[:up])

    # 'vote_count' is the channel name, 'update' is action name, hash is data attributes
    WebsocketRails[:vote_count].trigger 'update', { id: @article.id, count: @article.net_vote_count }
    redirect_to '/articles'

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_article.html.haml
.article
  %p= article.content
  / remote: true sends an AJAX request, so page refresh not required
  = button_to 'Upvote', article_votes_path(article, up: true), remote: true
  .vote-count{ data: { id: article.id } }
    = article.net_vote_count

app/views/articles/_form.html.haml
= form_for @article do |f|
  %p
  = f.text_area :content
  = f.submit

app/views/articles/index.html.haml
.article-container
= render @articles

app/views/articles/new.html.haml
= render 'form'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name == :notice ? "success" : "alert"}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Home', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
    %li.has-form
  .top-bar-section
    %ul.left
      %li.has-form
        .row.collapse
          .large-8.small-4.columns
            %input{placeholder: "Search articles", type: "text"}/
          .large-4.small-5.columns
            %a.alert.button.expand{href: "#"} Search
    %ul.hmenu.right
      = render 'devise/menu/registration_items'
      = render 'devise/menu/login_items'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SocialNewsSite
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    / required by Foundation5
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
    = render 'layouts/navigation'
    %main{role: "main"}
      = render 'layouts/messages'
      = yield